### ISSUE TITLE
Playback failed: Failed to resolve hostname websocket:443: No such host is known (websocket) com.neovisionaries.ws.client.WebSocketException

### ISSUE THREAD

**Issue by JingCTyagi** [rstudio/shinyloadtest#152]
To whom it may concern,

I was following the site https://rstudio.github.io/shinyloadtest/#:~:text=Load%20Testing%20Shiny%20Applications,users%20their%20application%20can%20support.
and downloaded [shinycannon-1.1.3-dd43f6b.jar](https://github.com/rstudio/shinycannon/releases/download/v1.1.3/shinycannon-1.1.3-dd43f6b.jar) to the directory you wish to run it in 
from this site  https://rstudio.github.io/shinyloadtest/articles/shinycannon.html#installation

OS: Windows 10, 
C:\GSA\GAO\Source\ShinyApps\LoadTesting>java -version
java version "16" 2021-03-16
Java(TM) SE Runtime Environment (build 16+36-2231)
Java HotSpot(TM) 64-Bit Server VM (build 16+36-2231, mixed mode, sharing)

when I run  the following command and got the errors below, any help would be greatly appreciated.
LoadTesting>java -jar ../shinycannon-1.1.3-dd43f6b.jar recording.log https://id_verification.ilx-test.net --workers 2 --loaded-duration-minutes 2 --output-dir run1
2022-03-03 06:55:01.374 INFO [thread00] - Detected target application type: R/Shiny
2022-03-03 06:55:01.380 INFO [progress] - Running: 0, Failed: 0, Done: 0
2022-03-03 06:55:01.381 INFO [thread00] - Waiting for warmup to complete
2022-03-03 06:55:01.381 INFO [thread01] - Warming up
2022-03-03 06:55:04.132 ERROR [thread01] - Playback failed: Failed to resolve hostname websocket:443: No such host is known (websocket)
com.neovisionaries.ws.client.WebSocketException: Failed to resolve hostname websocket:443: No such host is known (websocket)
        at com.neovisionaries.ws.client.SocketConnector.resolveHostname(SocketConnector.java:181)2022-03-03 06:55:04.134 INFO [thread01] - Running again
2022-03-03 06:55:04.553 ERROR [thread01] - Playback failed: Failed to resolve hostname websocket:443: websocket
com.neovisionaries.ws.client.WebSocketException: Failed to resolve hostname websocket:443: websocket
        at com.neovisionaries.ws.client.SocketConnector.resolveHostname(SocketConnector.java:181)2022-03-03 06:55:04.555 INFO [thread01] - Running again

Any idea and help would be greatly appreciated. Thanks for your help and time!

Thanks,
Jing

**Comment by schloerke** [comment]
@JingCTyagi Can you supply me with your recording.log file so I can try on my end?

**Comment by JingCTyagi** [comment]
FYI,

HI Barret,

Thanks for your prompt response!

Attached please find the recording.log file. I also included a simple recording1.log file too.

Please let me know if you have any questions.

Thanks,
Jing


On Thu, Mar 3, 2022 at 1:06 PM Tyagi, Jing C ***@***.******@***.***>> wrote:

**Comment by JingCTyagi** [comment]
> @JingCTyagi Can you supply me with your recording.log file so I can try on my end?

HI Barret, I just sent you the recording.log file by replying your email. Please let me know if you haven't received it.
[recording.log](https://github.com/rstudio/shinyloadtest/files/8180122/recording.log)

**Comment by JingCTyagi** [comment]
> @JingCTyagi Can you supply me with your recording.log file so I can try on my end?

Any update on this?
