### ISSUE TITLE
Shinycannon IllegalStateException

### ISSUE THREAD

**Issue by artiom33** [rstudio/shinyloadtest#21]
Hi,

I have tried to replicate the steps described in the README and it crashed on shinycannon.

When I run `shinyloadtest::record_session('https://beta.rstudioconnect.com/content/3239/')`
I get following error saved in the detail.log:
```
ERROR [main] 2018-07-19 13:45:33,501 (Main.kt:356) - Uncaught exception on main
java.lang.IllegalStateException: obj.get("created") must not be null
        at com.rstudio.shinycannon.Event$Companion.fromLine(Events.kt:79)
        at com.rstudio.shinycannon.MainKt.readEventLog(Main.kt:40)
        at com.rstudio.shinycannon.EnduranceTest.run(Main.kt:234)
        at com.rstudio.shinycannon.MainKt$main$1.invoke(Main.kt:369)
        at com.rstudio.shinycannon.MainKt$main$1.invoke(Main.kt)
        at com.xenomachina.argparser.SystemExitExceptionKt.mainBody(SystemExitException.kt:71)
        at com.xenomachina.argparser.SystemExitExceptionKt.mainBody$default(SystemExitException.kt:69)
        at com.rstudio.shinycannon.MainKt.main(Main.kt:322)

```

I am running it on Ubuntu Xenial, but I have tested it on multiple machines with the same results.
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```
I could not find the repository for shinycannon so I have decided to post it here.

Thanks,
Artiom

**Comment by paddybeefcakes** [comment]
I can confirm that I am also having this issue on Ubuntu 16.04.5 LTS

**Comment by alandipert** [comment]
@artiom33 @paddybeefcakes I believe we've fixed this problem by making newer builds of shinycannon available: https://rstudio.github.io/shinyloadtest/

We've also significantly updated the docs. If you find you still run into this error with the latest versions of shinyloadtest and shinycannon, please re-open.
