### ISSUE TITLE
ERROR [thread00] - Uncaught exception on thread00

### ISSUE THREAD

**Issue by Tazovsky** [rstudio/shinyloadtest#53]
I encountered error `Uncaught exception on thread00` on ubuntu 16.04 and centOS. Can you help with that?

### Ubuntu:

`shinycannon` version: `shinycannon_1.0.0-887bef2_amd64.deb`

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

Error:

```
$ shinycannon recording.log http://app-url --workers 1 --loaded-duration-minutes 2 --output-dir run1 --overwrite-output --log-level debug
2018-09-11 09:34:08.084 ERROR [thread00] - Uncaught exception on thread00
```

### CentOS:

```
$ rpm --query centos-release
centos-release-7-5.1804.el7.centos.2.x86_64

```

`shinycannon` version: `shinycannon-1.0.0-887bef2.x86_64.rpm `

Error:

```
$ shinycannon recording.log http://app-url --workers 2 --loaded-duration-minutes 2 --output-dir run1 --overwrite-output
Exception in thread "thread00" java.lang.IllegalStateException: Check failed.
	at com.rstudio.shinycannon.MainKt$main$1.invoke(Main.kt:398)
	at com.rstudio.shinycannon.MainKt$main$1.invoke(Main.kt)
	at com.xenomachina.argparser.SystemExitExceptionKt.mainBody(SystemExitException.kt:71)
	at com.xenomachina.argparser.SystemExitExceptionKt.mainBody$default(SystemExitException.kt:69)
	at com.rstudio.shinycannon.MainKt.main(Main.kt:382)

```

**Comment by Tazovsky** [comment]
Created another task in the right place: https://github.com/rstudio/shinycannon/issues/14

**Comment by alandipert** [comment]
Closing because rstudio/shinycannon#14 is closed.
